import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://ckd-ultrasound-ai.vercel.app/');
  await page.getByRole('textbox', { name: 'Email address' }).click();
  await page.getByRole('textbox', { name: 'Email address' }).fill('admin@ckdhealium.com');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Password' }).fill('A');
  await page.getByRole('textbox', { name: 'Password' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Password' }).fill('Admin@');
  await page.getByRole('textbox', { name: 'Password' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Password' }).fill('Admin@CKD');
  await page.getByRole('textbox', { name: 'Password' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Password' }).fill('Admin@CKD123');
  await page.getByRole('button', { name: 'Sign in' }).click();
  await page.getByRole('link', { name: 'Patients' }).click();
  await page.getByRole('button', { name: 'Add Patient' }).click();
  await page.getByRole('textbox', { name: 'Enter patient full name' }).click();
  await page.getByRole('textbox', { name: 'Enter patient full name' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Enter patient full name' }).fill('R');
  await page.getByRole('textbox', { name: 'Enter patient full name' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Enter patient full name' }).fill('Richa_pandey');
  await page.getByPlaceholder('Enter age').click();
  await page.getByRole('textbox', { name: 'Enter patient full name' }).click();
  await page.getByRole('textbox', { name: 'Enter patient full name' }).fill('Richa ');
  await page.getByRole('textbox', { name: 'Enter patient full name' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Enter patient full name' }).fill('Richa P');
  await page.getByRole('textbox', { name: 'Enter patient full name' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Enter patient full name' }).fill('Richa Pandey');
  await page.getByPlaceholder('Enter age').click();
  await page.getByPlaceholder('Enter age').fill('21');
  await page.getByRole('combobox', { name: 'Gender *' }).click();
  await page.getByRole('option', { name: 'Female' }).click();
  await page.getByRole('button', { name: 'Create Patient' }).click();
  await expect(page.getByText('Patient Created Successfully!')).toBeVisible();
  await page.locator('#radix-_r_2n_').click();
  await page.getByRole('menuitem', { name: 'Edit Patient' }).click();
  await page.getByRole('textbox', { name: 'Enter patient full name' }).click();
  await page.getByRole('textbox', { name: 'Enter patient full name' }).fill('Richa Pandey_');
  await page.getByRole('textbox', { name: 'Enter patient full name' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Enter patient full name' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Enter patient full name' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Enter patient full name' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Enter patient full name' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Enter patient full name' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Enter patient full name' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Enter patient full name' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Enter patient full name' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Enter patient full name' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Enter patient full name' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Enter patient full name' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Enter patient full name' }).fill('Richa_Pandey_');
  await page.getByRole('textbox', { name: 'Enter patient full name' }).click();
  await page.getByRole('textbox', { name: 'Enter patient full name' }).click();
  await page.getByRole('textbox', { name: 'Enter patient full name' }).fill('Richa_Pandey_test');
  await page.getByRole('button', { name: 'Update Patient' }).click();
  await expect(page.getByText('Patient Updated Successfully!')).toBeVisible();
  await page.locator('#radix-_r_3q_').click();
  await page.getByRole('menuitem', { name: 'Delete Patient' }).click();
  await page.getByRole('button', { name: 'Delete' }).click();
  await expect(page.getByText('Test Richa1')).not.toBeVisible();
  await expect(page.getByText('Richa_test')).toBeVisible();
});